### ISSUE TITLE
validate reservation.yaml

### ISSUE THREAD

**Issue by ivotron** [BeyondTheClouds/enos#174]
Would be useful to have a `--validate` flag that validates the YAML for a given subcommand. For example: `enos up --validate` would check whether the YAML file contains all the necessary info for executing the `up` operation.

**Comment by rcherrueau** [comment]
Like the idea. Implementing the `--validate` for the `up` should be an easy task thanks to the [`default_config`](https://github.com/BeyondTheClouds/enos/blob/417b3caf2c866e6a90d0b86070942029ed11332b/enos/provider/provider.py#L30)  method in a provider. But, for the `enos os` that should validate the inventory file, or for `enos bench` that should verify the workload, the validation gets tough.

Instead of a `--validate`, I propose something like `enos new my-exp --provider=chameleon` that makes a `my-exp` directory with a reservation file dedicated to chameleon, plus a default inventory and workload. It should limit the risk of wrong configurations.

@ivotron, @BeyondTheClouds/enos  what do you think?

In a second time we could implement a better cli, à la `npm init` for instance. It will ask you to fill required fields and avoid the manual edition of the reservation file.

**Comment by msimonin** [comment]
Let's start hacking this ;)
