### ISSUE TITLE
lease name is hardcoded in chameleonbaremetal provider

### ISSUE THREAD

**Issue by rizaon** [BeyondTheClouds/enos#232]
get_reservation function in chameleonbaremetal provider always check lease with name "enos-lease" only. It should use the lease name defined in configuration.

**Comment by msimonin** [comment]
Oh yes, it seems we check the `enos_lease` : 

https://github.com/BeyondTheClouds/enos/blob/e2e1ae94a620becaeead3763430cf155c411f693/enos/provider/chameleonbaremetal.py#L62

But allow to create a reservation using a custom name:

https://github.com/BeyondTheClouds/enos/blob/e2e1ae94a620becaeead3763430cf155c411f693/enos/provider/chameleonbaremetal.py#L111

We could pass the config object in the `get_reservation` function.

Let me know if want to fix it: I suggest to patch the `stable/pike` branch first.
So that we can release `3.0.2` with it.

**Comment by rizaon** [comment]
Please check the submitted PR

Also, I notice that the 5 extra ips are never used. Shall we remove it?

https://github.com/BeyondTheClouds/enos/blob/e2e1ae94a620becaeead3763430cf155c411f693/enos/provider/chameleonbaremetal.py#L166

**Comment by msimonin** [comment]
Actually those ips are used later in the workflow to give a virtual ip to `haproxy`, `grafana`, ...
They are returned part of the network description returned by the provider and used here :

https://github.com/BeyondTheClouds/enos/blob/e2e1ae94a620becaeead3763430cf155c411f693/enos/provider/chameleonbaremetal.py#L200

https://github.com/BeyondTheClouds/enos/blob/e2e1ae94a620becaeead3763430cf155c411f693/enos/provider/openstack.py#L390

and poped from the pool of available ip here :

https://github.com/BeyondTheClouds/enos/blob/e2e1ae94a620becaeead3763430cf155c411f693/enos/enos.py#L162

**Comment by rizaon** [comment]
Thank you for the explanation. I guess this issue can be closed.
