### ISSUE TITLE
Enos comes with enoslib v6

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#340]
The requires of enos says `enoslib>=5.4.4`.  After a fresh installation today, enos came with the new enoslib v6.  

Supporting enoslib v6 implies a lot of modifications.  It may be a better idea to stick to enoslib 5.* right now ?

**Comment by msimonin** [comment]
Oh :(
As a quick fix, we coud stick to `<6.0.0`.
We could update later to the v6.

**Comment by rcherrueau** [comment]
I am on it.  I have to do other deployments with enos and suspect other fixes here and there (e.g., support docker authentication to circumvent the new rate limitation).  

If you are agree, I would prefer to make one unique PR (with as many commits as fixed issues).

**Comment by msimonin** [comment]
sure,
Regarding the docker limits on g5k, we could use the registry mirror deployed by the infra team: `http://docker-cache.<site>.grid5000.fr`. To determine the `site`, we can use the function `get_cluster_site` from EnOSlib (in `g5k_api_utils.py`)
(also we could use the docker service from EnOSlib instead of the specific implementation)

**Comment by msimonin** [comment]
for the record:  https://gitlab.inria.fr/discovery/enoslib/-/issues/93
